### PR TITLE
History

### PR DESCRIPTION
**Pull request by JiaoJiao123**

### CODE REVIEW

**Comment by JiaoJiao123** [comment]
@zhx828 Yeah that's a good point. I was aware of that, and plan to do it in another PR. It is hard to test without backup part, I will add it in this PR.

**Comment by JiaoJiao123** [comment]
@zhx828 history backup part is added

**Comment by JiaoJiao123** [comment]
@zhx828 getHistoryData in history backup part is updated. 
When we save JS array as value for collaborative map, it will change the array length to read only. So we can not push items to it until using Array.from() to convert it to a normal array. 
We don't need to use Array.from() when backing up since no need to modify anything.

**Comment by zhx828** [comment]
@JiaoJiao123 thanks! Good to know. The code looks good. But let me do some functional tests before merging

**Pull request merged**
