### PR TITLE
Switch to spotify/dockerfile-maven + webapp-runner

### PR DESCRIPTION
**Pull request by inodb**
Using webapp-runner provides an easier command line interface to tomcat imo.
Change the docker image also to mount at root instead of at /oncokb/ path.
Changed the docker generation to use spotify/dockerfile-maven, this is
recommended new way to generate docker files using maven.

### CODE REVIEW

**Comment by inodb** [comment]
@ersinciftci 	☝️

**Comment by ersinciftci** [comment]
Yeah I think it's better to have a Dockerfile that everyone can understand instead of having the same info in pom.xml

**Comment by ersinciftci** [comment]
I thought it would make things easier if we didn't have a Dockerfile when I first made this change, but I don't think like that anymore :)

**Comment by inodb** [comment]
@ersinciftci agreed - being able to see the Dockerfile is useful. I guess that's why spotify/docker-maven-plugin now recommends to use spotify/dockerfile-maven

**Pull request merged**
